apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hackathon-solution
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-boot-basic
    apps.tanzu.vmware.com/has-tests: 'true'
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: '17'
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      memory: 1Gi
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: '1'
      autoscaling.knative.dev/maxScale: '3'
      autoscaling.knative.dev/window: '120s'
      autoscaling.knative.dev/target: '5'
      autoscaling.knative.dev/metric: rps
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
